name: Bug
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
