name: Epic
description: Large feature or initiative
labels: ["epic"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary

  - type: textarea
    id: goals
    attributes:
      label: Goals

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
